#!/usr/bin/env python3
"""Build the multi-character qBittorrent Alternative WebUI pack.

Input : stock WebUI (release-5.2.4 src/webui/www) + this folder (src/).
Output: dist/anime-theme/{public,private,README.md} at the repository root.
Run again after adding a character to themes/manifest.js (generates its icon set).

Set QBT_WEBUI_SRC to the stock www directory. The default is a qBittorrent
checkout next to this repository (../qBittorrent/src/webui/www).
"""
import json, os, re, shutil, tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
STOCK = Path(os.environ.get("QBT_WEBUI_SRC", ROOT.parent / "qBittorrent" / "src" / "webui" / "www"))
OUT = ROOT / "dist" / "anime-theme"
FONT_DIR = HERE / "fonts"
FONT_FILES = ("Cinzel.ttf", "PlayfairDisplay.ttf", "CormorantGaramond.ttf")
# stock icon colour -> palette role
ROLE = {
    "#1e90ff": "primary", "#4169e1": "primaryDeep", "#6495ed": "primarySoft",
    "#f00": "error", "#ff0000": "error",
    "#32cd32": "success", "#3cb371": "successAlt", "#008000": "successDeep",
    "#ff8c00": "warn", "#cd853f": "warnAlt", "#008080": "teal",
    "#999": "neutral", "#808080": "neutral", "gray": "neutral", "#c4c4c4": "neutralLight",
    "#8250df": "extra",
}
TRAY = {"#72b4f5": "#e0263a", "#356ebf": "#5a0a10", "#daefff": "#f5d77a"}
COLOR_RE = re.compile(r'((?:fill|stroke|stop-color)\s*[=:]\s*"?)(#[0-9a-fA-F]{3,6}|gray)\b')


def load_manifest():
    t = (HERE / "themes/manifest.js").read_text()
    m = re.search(r"^window\.ANIME_THEMES\s*=\s*", t, re.M)
    t = t[m.end():]
    return json.loads(t[: t.rindex("}") + 1])


def recolor(svg_text, palette, extra=None):
    def sub(m):
        c = m.group(2).lower()
        if extra and c in extra:
            return m.group(1) + extra[c]
        role = ROLE.get(c)
        return m.group(1) + (palette.get(role, m.group(2)) if role else m.group(2))
    return COLOR_RE.sub(sub, svg_text)


def main():
    if not (STOCK / "public").is_dir() or not (STOCK / "private").is_dir():
        raise SystemExit(
            f"stock WebUI not found at {STOCK}\n"
            "Set QBT_WEBUI_SRC to qBittorrent release-5.2.4 src/webui/www")
    man = load_manifest()
    chars = man["characters"]
    default = next(c for c in chars if c["id"] == man["default"])
    ids = [c["id"] for c in chars]
    assert len(ids) == len(set(ids)), "duplicate character id"

    screens = OUT / "screens"
    keep = None
    if screens.exists():
        keep = Path(tempfile.mkdtemp(prefix="anime-screens-"))
        shutil.copytree(screens, keep / "screens")
    shutil.rmtree(OUT, ignore_errors=True)
    OUT.mkdir(parents=True)
    for d in ("public", "private"):
        shutil.copytree(STOCK / d, OUT / d)
    if keep:
        shutil.copytree(keep / "screens", screens)
        shutil.rmtree(keep, ignore_errors=True)

    # icons ---------------------------------------------------------------
    stock_icons = sorted((STOCK / "private/images").glob("*.svg"))
    names = [p.stem for p in stock_icons]
    for p in stock_icons:   # stock folder = default character (fallback for browsers without img content:)
        (OUT / "private/images" / p.name).write_text(recolor(p.read_text(), default["iconPalette"]))
    tray = OUT / "public/images/qbittorrent-tray.svg"
    tray.write_text(recolor(tray.read_text(), default["iconPalette"], TRAY))

    themes_out = OUT / "public/themes"
    themes_out.mkdir()
    for c in chars:
        src = HERE / "themes" / c["id"]
        for req in ("theme.css", "bg-dark.webp", "bg-light.webp", "avatar.webp", "favicon.png"):
            assert (src / req).exists(), f"{c['id']}: missing {req}"
        shutil.copytree(src, themes_out / c["id"])
        if c.get("icons"):
            idir = themes_out / c["id"] / "icons"; idir.mkdir(exist_ok=True)
            for p in stock_icons:
                (idir / p.name).write_text(recolor(p.read_text(), c["iconPalette"]))
    for f in ("manifest.js", "theme-loader.js", "picker.js"):
        shutil.copy(HERE / "themes" / f, themes_out / f)
    (themes_out / "icon-names.js").write_text(
        "/* generated by build.py - icon names that characters may override */\nwindow.ANIME_ICON_NAMES = "
        + json.dumps(names) + ";\n")

    # CSS -----------------------------------------------------------------
    url_re = re.compile(r'url\("\.\./images/([A-Za-z0-9_-]+)\.svg"\)')
    for css in (OUT / "private/css").glob("*.css"):
        t = css.read_text()
        t2 = url_re.sub(lambda m: f'var(--qi-{m.group(1)}, url("../images/{m.group(1)}.svg"))' if m.group(1) in names else m.group(0), t)
        if t2 != t:
            css.write_text(t2)
    rules = "\n".join(f'img[src*="images/{n}.svg"] {{ content: var(--qi-{n}); }}' for n in names)
    (OUT / "public/css/anime-icons.css").write_text(
        "/* generated by build.py: swap <img> icons for the active character's set (vars set by theme-loader.js) */\n" + rules + "\n")
    shutil.copy(HERE / "fonts.css", OUT / "public/css/anime-fonts.css")
    shutil.copy(HERE / "anime-login.css", OUT / "public/css/anime-login.css")
    shutil.copy(HERE / "anime.css", OUT / "private/css/anime.css")
    (OUT / "public/fonts").mkdir()
    for n in FONT_FILES:
        src = FONT_DIR / n
        if not src.is_file():
            raise SystemExit(f"missing font {src}")
        shutil.copy(src, OUT / "public/fonts" / n)

    # HTML ----------------------------------------------------------------
    V = "?v=${CACHEID}-p" + str(man.get("version", "1"))  # pack version busts the 12h browser cache without a restart
    head_common = (
        f'    <!-- anime-theme -->\n'
        f'    <link rel="stylesheet" type="text/css" href="css/anime.css{V}">\n'
        f'    <link rel="stylesheet" type="text/css" href="css/anime-icons.css{V}">\n'
        f'    <script src="themes/manifest.js{V}"></script>\n'
        f'    <script src="themes/icon-names.js{V}"></script>\n'
        f'    <script src="themes/theme-loader.js{V}"></script>\n')
    n = 0
    for html in (OUT / "private").rglob("*.html"):
        t = html.read_text()
        if "</head>" not in t or "css/style.css" not in t or html.parent.name == "views":
            continue
        assert t.count("</head>") == 1
        ins = head_common
        if html.name == "index.html" and html.parent.name == "private":
            ins += f'    <script defer src="themes/picker.js{V}"></script>\n'
        html.write_text(t.replace("</head>", ins + "    <!-- /anime-theme -->\n</head>")); n += 1
    idx = OUT / "public/index.html"
    t = idx.read_text()
    login_head = (
        f'    <!-- anime-theme -->\n'
        f'    <link rel="stylesheet" type="text/css" href="css/anime-login.css{V}">\n'
        f'    <script src="themes/manifest.js{V}"></script>\n'
        f'    <script src="themes/theme-loader.js{V}" data-page="login"></script>\n'
        f'    <script defer src="themes/picker.js{V}"></script>\n'
        f'    <!-- /anime-theme -->\n')
    t = t.replace("</head>", login_head + "</head>")
    old = '<img src="images/qbittorrent-tray.svg" alt="qBittorrent logo">'
    assert old in t
    t = t.replace(old, f'<img src="themes/{default["id"]}/avatar.webp" alt="{default["name"]}" data-anime-avatar> <!-- anime-theme -->')
    idx.write_text(t)
    shutil.copy(HERE / "README.md", OUT / "README.md")
    print(f"characters={ids} icons={len(names)} private_html_patched={n}")


if __name__ == "__main__":
    main()
